global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'employee-management'
    metrics_path: /api/employee/metrics
    static_configs:
      - targets: [ 'api-gateway-for-nest:4004' ]
        labels:
          service: 'employee'

  - job_name: 'tenan-management'
    metrics_path: /api/tenan/metrics
    static_configs:
      - targets: [ 'api-gateway-for-nest:4004' ]
        labels:
          service: 'tenan'